import = [
	"~/.config/alacritty/tokyo-night.toml",
]

shell = "/bin/zsh"

# live config reload
#live_config_reload = true

[window]
#opacity = 1 

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block" }

vi_mode_style = { shape = "Beam", blinking = "On" }

blink_interval = 500

thickness = 0.2

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
